name: anypkgs

on:
  push:
    branches:
    - master
    - main

env:
  APP_NAME: ospkgs
  DOCKER_REPO: devilf/ospkgs

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout codes'
      uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Bildx
      uses: docker/setup-buildx-action@v1
    - name: Login to dockerhub
      uses: docker/login-action@v1
      with:
        username: ${{secrets.DOCKER_HUB_USERNAME}}
        password: ${{secrets.DOCKER_HUB_PASSWORD}}
    - name: Get version
      run: echo APP_VERSION=`git describe --tags --always` >> $GITHUB_ENV
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        file: build/template/Dockerfile.template-centos
        push: true
        platforms: |
          linux/arm
          linux/amd
        build-args: |
          APP_NAME=${{env.APP_NAME}}
          APP_VERSION=${{env.APP_VERSION}}
        tags: |
          devilf/ospkgs:latest
