name: anypkgs

on:
  push:
    branches:
    - master
    - main

env:
  APP_NAME: ospkgs
  DOCKER_REPO: devilf/ospkgs

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include:
        - version: 7.9.2009
          image: centos
          platform: linux/amd64,linux/arm64
        - version: 7.8.2003
          image: centos
          platform: linux/amd64
        - version: 7.7.1908
          image: centos
          platform: linux/amd64
        - version: 7.6.1810
          image: centos
          platform: linux/amd64
        - version: 7.5.1804
          image: centos
          platform: linux/amd64
    steps:
    - name: 'Checkout codes'
      uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Bildx
      uses: docker/setup-buildx-action@v1
    - name: Login to dockerhub
      uses: docker/login-action@v1
      with:
        username: ${{secrets.DOCKER_HUB_USERNAME}}
        password: ${{secrets.DOCKER_HUB_PASSWORD}}
    - name: Get version
      run: echo APP_VERSION=`git describe --tags --always` >> $GITHUB_ENV
    - name: Gen Dockerfile
      shell: bash
      run: |
        sed "s/OS_VERSION/${{matrix.version}}/g" build/template/Dockerfile.template-centos7 > Dockerfile.${{matrix.image}}-${{matrix.version}}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile.${{matrix.image}}-${{matrix.version}}
        push: ${{github.event_name != 'pull_request'}}
        platforms: ${{matrix.platform}}
        # build-args: |
        #   APP_NAME=${{env.APP_NAME}}
        #   APP_VERSION=${{env.APP_VERSION}}
        tags: |
          devilf/os-${{matrix.image}}:${{matrix.version}}
    - name: Gen new dockerfile
      shell: bash
      run: |
        echo -e "FROM scratch\nCOPY --from=devilf/os-${{matrix.image}}:${{matrix.version}} / /" > Dockerfile.release.${{matrix.image}}-${{matrix.version}}
    - name: Build image to local
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile.release.${{matrix.image}}-${{matrix.version}}
        platforms: ${{matrix.platform}}
        outputs: type=local,dest=./
    - name: Prepare for upload package
      shell: bash
      run: |
        ls -l
        ls -l centos
        mv linux_amd64/centos centos
        tar -I pigz -cf os-${{matrix.image}}-${{matrix.version}}-amd64.tar.gz offline --remove-files
        mv linux_arm64/centos centos
        tar -I pigz -cf os-${{matrix.image}}-${{matrix.version}}-arm64.tar.gz offline --remove-files
        sha256sum os-${{matrix.image}}-${{matrix.version}}-{amd64,arm64}.tar.gz > os-${{matrix.image}}-${{matrix.version}}.sha256sum.txt
    - name: Release and upload packages
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: |
          os-${{matrix.image}}-${{matrix.version}}-amd64.tar.gz
          os-${{matrix.image}}-${{matrix.version}}-arm64.tar.gz
          os-${{matrix.image}}-${{matrix.version}}.sha256sum.txt
